package de.vivistra.telegrambot.model.message;

public enum MessageType {
	TEXT_MESSAGE, IMAGE_MESSAGE, AUDIO_MESSAGE, VIDEO_MESSAGE, DOCUMENT_MESSAGE, STICKER_MESSAGE, CONTACT_MESSAGE, LOCATION_MESSAGE, UNHANDLED_MESSAGE
}
